# Jenkins Job Configuration for uniteDiscord-ci
# This file documents the job configuration. Apply via Jenkins UI or JCasC plugin.
#
# IMPORTANT: This pipeline uses the Generic Webhook Trigger Plugin
# GitHub webhook URL: https://jenkins.kindash.com/generic-webhook-trigger/invoke?token=uniteDiscord-ci
#
# To apply this configuration:
# 1. If using JCasC plugin: Add this to your Jenkins configuration
# 2. If using UI: Use these settings when creating/updating the job

jobs:
  - script: >
      pipelineJob('uniteDiscord-ci') {
        description('uniteDiscord CI Pipeline - runs full CI workflow (lint, unit tests, build)')

        properties {
          githubProjectUrl('https://github.com/steiner385/uniteDiscord')

          buildDiscarder {
            logRotator {
              numToKeepStr('30')
            }
          }

          disableConcurrentBuilds {
            abortPrevious(true)
          }
        }

        // Triggers are defined in Jenkinsfile using GenericTrigger
        // The pipeline extracts branch/commit from webhook payload

        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/steiner385/uniteDiscord.git')
                  credentials('github-credentials')
                }
                // Branch is determined dynamically from webhook payload
                branches('*/main')
              }
            }
            scriptPath('.jenkins/Jenkinsfile')
            lightweight(false)
          }
        }
      }
