/**
 * AI service event definitions
 */

import type { BaseEvent } from './base.js';

/**
 * Event types for AI service
 */
export const AI_EVENT_TYPES = {
  RESPONSE_ANALYZED: 'response.analyzed',
  COMMON_GROUND_GENERATED: 'common-ground.generated',
  COMMON_GROUND_UPDATED: 'common-ground.updated',
} as const;

/**
 * Feedback item generated by AI analysis
 */
export interface AnalysisFeedback {
  /** Type of feedback */
  type: 'fallacy' | 'inflammatory' | 'unsourced' | 'bias' | 'affirmation';
  /** Specific subtype (e.g., fallacy name) */
  subtype?: string;
  /** User-facing suggestion text */
  suggestionText: string;
  /** AI reasoning for transparency */
  reasoning: string;
  /** Confidence score (0.00-1.00) */
  confidenceScore: number;
  /** Educational resources related to this feedback */
  educationalResources?: Array<{
    title: string;
    url: string;
  }>;
}

/**
 * Payload for response.analyzed event
 * Published after AI analyzes a response for quality and argumentation
 */
export interface ResponseAnalyzedPayload {
  /** ID of the analyzed response */
  responseId: string;
  /** Topic the response belongs to */
  topicId: string;
  /** Author of the response */
  authorId: string;
  /** AI-generated feedback items */
  feedback: AnalysisFeedback[];
  /** Whether factual claims were detected */
  containsFactualClaims: boolean;
  /** Propositions the response relates to */
  relatedPropositions: Array<{
    propositionId: string;
    relevanceScore: number;
  }>;
  /** Model version used for analysis */
  modelVersion: string;
  /** When analysis was completed */
  analyzedAt: string;
}

/**
 * Event published when AI completes analysis of a response
 */
export interface ResponseAnalyzedEvent
  extends BaseEvent<typeof AI_EVENT_TYPES.RESPONSE_ANALYZED, ResponseAnalyzedPayload> {
  type: typeof AI_EVENT_TYPES.RESPONSE_ANALYZED;
}

/**
 * Agreement zone identified in common ground analysis
 */
export interface AgreementZone {
  /** Description of the agreement */
  description: string;
  /** Confidence level (0.00-1.00) */
  confidence: number;
  /** Proposition IDs that support this agreement */
  propositionIds: string[];
  /** Percentage of participants who agree */
  participantPercentage: number;
}

/**
 * Misunderstanding identified in common ground analysis
 */
export interface Misunderstanding {
  /** Description of the misunderstanding */
  description: string;
  /** Term being used differently */
  term: string;
  /** Different definitions used by participants */
  definitions: Array<{
    definition: string;
    userIds: string[];
  }>;
  /** Propositions affected by this misunderstanding */
  affectedPropositions: string[];
}

/**
 * Genuine disagreement identified in common ground analysis
 */
export interface GenuineDisagreement {
  /** Description of the disagreement */
  description: string;
  /** Underlying values in conflict */
  underlyingValues: string[];
  /** Moral foundations involved */
  moralFoundations: Array<'care' | 'fairness' | 'loyalty' | 'authority' | 'sanctity' | 'liberty'>;
  /** Related proposition IDs */
  propositionIds: string[];
}

/**
 * Payload for common-ground.generated event
 * Published when AI generates a common ground analysis for a topic
 */
export interface CommonGroundGeneratedPayload {
  /** Topic that was analyzed */
  topicId: string;
  /** Version number of the analysis */
  version: number;
  /** Identified areas of agreement */
  agreementZones: AgreementZone[];
  /** Identified misunderstandings */
  misunderstandings: Misunderstanding[];
  /** Identified genuine disagreements */
  genuineDisagreements: GenuineDisagreement[];
  /** Overall consensus score (0.00-1.00) */
  overallConsensusScore?: number;
  /** Participant count at time of generation */
  participantCountAtGeneration: number;
  /** Response count at time of generation */
  responseCountAtGeneration: number;
  /** Model version used */
  modelVersion: string;
  /** When analysis was generated */
  generatedAt: string;
}

/**
 * Event published when common ground analysis is generated
 */
export interface CommonGroundGeneratedEvent
  extends BaseEvent<typeof AI_EVENT_TYPES.COMMON_GROUND_GENERATED, CommonGroundGeneratedPayload> {
  type: typeof AI_EVENT_TYPES.COMMON_GROUND_GENERATED;
}

/**
 * Payload for common-ground.updated event
 * Published when a new version of common ground analysis is generated for a topic
 */
export interface CommonGroundUpdatedPayload {
  /** Topic that was analyzed */
  topicId: string;
  /** Previous version number */
  previousVersion: number;
  /** New version number */
  newVersion: number;
  /** Previous analysis data */
  previousAnalysis: {
    agreementZones: AgreementZone[];
    misunderstandings: Misunderstanding[];
    genuineDisagreements: GenuineDisagreement[];
    overallConsensusScore?: number;
  };
  /** New analysis data */
  newAnalysis: {
    agreementZones: AgreementZone[];
    misunderstandings: Misunderstanding[];
    genuineDisagreements: GenuineDisagreement[];
    overallConsensusScore?: number;
  };
  /** Summary of what changed */
  changes: {
    /** Number of new agreement zones found */
    newAgreementZones: number;
    /** Number of agreement zones removed */
    removedAgreementZones: number;
    /** Number of new misunderstandings identified */
    newMisunderstandings: number;
    /** Number of misunderstandings resolved */
    resolvedMisunderstandings: number;
    /** Number of new disagreements identified */
    newDisagreements: number;
    /** Change in overall consensus score */
    consensusScoreChange?: number;
  };
  /** Reason for the update */
  reason: 'response_threshold' | 'time_threshold' | 'manual_trigger';
  /** Participant count at time of update */
  participantCountAtUpdate: number;
  /** Response count at time of update */
  responseCountAtUpdate: number;
  /** Response count since last version */
  newResponsesSinceLastVersion: number;
  /** Model version used */
  modelVersion: string;
  /** When update was generated */
  updatedAt: string;
}

/**
 * Event published when a new version of common ground analysis is generated
 */
export interface CommonGroundUpdatedEvent
  extends BaseEvent<typeof AI_EVENT_TYPES.COMMON_GROUND_UPDATED, CommonGroundUpdatedPayload> {
  type: typeof AI_EVENT_TYPES.COMMON_GROUND_UPDATED;
}

/**
 * Union type of all AI service events
 */
export type AIEvent = ResponseAnalyzedEvent | CommonGroundGeneratedEvent | CommonGroundUpdatedEvent;
