/**
 * AI service event definitions
 */

import type { BaseEvent } from './base.js';

/**
 * Event types for AI service
 */
export const AI_EVENT_TYPES = {
  RESPONSE_ANALYZED: 'response.analyzed',
  COMMON_GROUND_GENERATED: 'common-ground.generated',
} as const;

/**
 * Feedback item generated by AI analysis
 */
export interface AnalysisFeedback {
  /** Type of feedback */
  type: 'fallacy' | 'inflammatory' | 'unsourced' | 'bias' | 'affirmation';
  /** Specific subtype (e.g., fallacy name) */
  subtype?: string;
  /** User-facing suggestion text */
  suggestionText: string;
  /** AI reasoning for transparency */
  reasoning: string;
  /** Confidence score (0.00-1.00) */
  confidenceScore: number;
  /** Educational resources related to this feedback */
  educationalResources?: Array<{
    title: string;
    url: string;
  }>;
}

/**
 * Payload for response.analyzed event
 * Published after AI analyzes a response for quality and argumentation
 */
export interface ResponseAnalyzedPayload {
  /** ID of the analyzed response */
  responseId: string;
  /** Topic the response belongs to */
  topicId: string;
  /** Author of the response */
  authorId: string;
  /** AI-generated feedback items */
  feedback: AnalysisFeedback[];
  /** Whether factual claims were detected */
  containsFactualClaims: boolean;
  /** Propositions the response relates to */
  relatedPropositions: Array<{
    propositionId: string;
    relevanceScore: number;
  }>;
  /** Model version used for analysis */
  modelVersion: string;
  /** When analysis was completed */
  analyzedAt: string;
}

/**
 * Event published when AI completes analysis of a response
 */
export interface ResponseAnalyzedEvent
  extends BaseEvent<typeof AI_EVENT_TYPES.RESPONSE_ANALYZED, ResponseAnalyzedPayload> {
  type: typeof AI_EVENT_TYPES.RESPONSE_ANALYZED;
}

/**
 * Agreement zone identified in common ground analysis
 */
export interface AgreementZone {
  /** Description of the agreement */
  description: string;
  /** Confidence level (0.00-1.00) */
  confidence: number;
  /** Proposition IDs that support this agreement */
  propositionIds: string[];
  /** Percentage of participants who agree */
  participantPercentage: number;
}

/**
 * Misunderstanding identified in common ground analysis
 */
export interface Misunderstanding {
  /** Description of the misunderstanding */
  description: string;
  /** Term being used differently */
  term: string;
  /** Different definitions used by participants */
  definitions: Array<{
    definition: string;
    userIds: string[];
  }>;
  /** Propositions affected by this misunderstanding */
  affectedPropositions: string[];
}

/**
 * Genuine disagreement identified in common ground analysis
 */
export interface GenuineDisagreement {
  /** Description of the disagreement */
  description: string;
  /** Underlying values in conflict */
  underlyingValues: string[];
  /** Moral foundations involved */
  moralFoundations: Array<'care' | 'fairness' | 'loyalty' | 'authority' | 'sanctity' | 'liberty'>;
  /** Related proposition IDs */
  propositionIds: string[];
}

/**
 * Payload for common-ground.generated event
 * Published when AI generates a common ground analysis for a topic
 */
export interface CommonGroundGeneratedPayload {
  /** Topic that was analyzed */
  topicId: string;
  /** Version number of the analysis */
  version: number;
  /** Identified areas of agreement */
  agreementZones: AgreementZone[];
  /** Identified misunderstandings */
  misunderstandings: Misunderstanding[];
  /** Identified genuine disagreements */
  genuineDisagreements: GenuineDisagreement[];
  /** Overall consensus score (0.00-1.00) */
  overallConsensusScore?: number;
  /** Participant count at time of generation */
  participantCountAtGeneration: number;
  /** Response count at time of generation */
  responseCountAtGeneration: number;
  /** Model version used */
  modelVersion: string;
  /** When analysis was generated */
  generatedAt: string;
}

/**
 * Event published when common ground analysis is generated
 */
export interface CommonGroundGeneratedEvent
  extends BaseEvent<typeof AI_EVENT_TYPES.COMMON_GROUND_GENERATED, CommonGroundGeneratedPayload> {
  type: typeof AI_EVENT_TYPES.COMMON_GROUND_GENERATED;
}

/**
 * Union type of all AI service events
 */
export type AIEvent = ResponseAnalyzedEvent | CommonGroundGeneratedEvent;
