openapi: 3.0.3
info:
  title: Discussion API
  description: API for managing discussions within topics
  version: 1.0.0

paths:
  /discussions:
    post:
      summary: Create a new discussion
      description: Create a new discussion within a topic with an initial response
      operationId: createDiscussion
      tags:
        - discussions
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateDiscussionRequest'
      responses:
        '201':
          description: Discussion created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscussionResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user not verified or rate limit exceeded
        '429':
          description: Rate limit exceeded (5 discussions per day)

    get:
      summary: List discussions
      description: Get discussions for a specific topic with filtering and sorting
      operationId: listDiscussions
      tags:
        - discussions
      security:
        - bearerAuth: []
      parameters:
        - name: topicId
          in: query
          required: true
          schema:
            type: string
            format: uuid
          description: Filter by topic ID
        - name: status
          in: query
          schema:
            type: string
            enum: [ACTIVE, ARCHIVED, DELETED]
            default: ACTIVE
          description: Filter by discussion status
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [recency, activity, responseCount]
            default: activity
          description: Sort order
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number (50 discussions per page)
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Number of discussions per page
      responses:
        '200':
          description: List of discussions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscussionListResponse'
        '400':
          description: Invalid query parameters
        '401':
          description: Unauthorized

  /discussions/{discussionId}:
    get:
      summary: Get discussion details
      description: Get a single discussion with all responses (threaded)
      operationId: getDiscussion
      tags:
        - discussions
      security:
        - bearerAuth: []
      parameters:
        - name: discussionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for responses (50 responses per page)
      responses:
        '200':
          description: Discussion details with responses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscussionDetailResponse'
        '401':
          description: Unauthorized
        '404':
          description: Discussion not found

    delete:
      summary: Delete a discussion
      description: Delete a discussion (only by creator)
      operationId: deleteDiscussion
      tags:
        - discussions
      security:
        - bearerAuth: []
      parameters:
        - name: discussionId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Discussion deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - not the discussion creator
        '404':
          description: Discussion not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateDiscussionRequest:
      type: object
      required:
        - topicId
        - title
        - initialResponse
      properties:
        topicId:
          type: string
          format: uuid
          description: ID of the topic this discussion belongs to
        title:
          type: string
          minLength: 10
          maxLength: 200
          description: Discussion title
        initialResponse:
          type: object
          required:
            - content
          properties:
            content:
              type: string
              minLength: 50
              maxLength: 25000
              description: Initial response content (max 5,000 words ≈ 25,000 chars)
            citations:
              type: array
              maxItems: 10
              items:
                $ref: '#/components/schemas/CitationInput'

    CitationInput:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          maxLength: 2048
          description: Citation URL (will be validated for SSRF)
        title:
          type: string
          maxLength: 500
          description: Optional citation title/description

    DiscussionResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        topicId:
          type: string
          format: uuid
        title:
          type: string
        status:
          type: string
          enum: [ACTIVE, ARCHIVED, DELETED]
        creator:
          $ref: '#/components/schemas/UserSummary'
        responseCount:
          type: integer
          description: Total number of responses (including nested)
        participantCount:
          type: integer
          description: Number of unique participants
        lastActivityAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    DiscussionListResponse:
      type: object
      properties:
        discussions:
          type: array
          items:
            $ref: '#/components/schemas/DiscussionResponse'
        pagination:
          $ref: '#/components/schemas/Pagination'

    DiscussionDetailResponse:
      allOf:
        - $ref: '#/components/schemas/DiscussionResponse'
        - type: object
          properties:
            responses:
              type: array
              items:
                $ref: '#/components/schemas/ResponseNode'
            responsePagination:
              $ref: '#/components/schemas/Pagination'

    ResponseNode:
      type: object
      properties:
        id:
          type: string
          format: uuid
        discussionId:
          type: string
          format: uuid
        parentId:
          type: string
          format: uuid
          nullable: true
          description: Parent response ID (null for top-level responses)
        author:
          $ref: '#/components/schemas/UserSummary'
        content:
          type: string
          description: Response content (may be "[deleted by author]" for soft-deleted)
        citations:
          type: array
          items:
            $ref: '#/components/schemas/Citation'
        version:
          type: integer
          description: Version number for optimistic locking
        isDeleted:
          type: boolean
          description: True if soft-deleted
        isEdited:
          type: boolean
          description: True if edited after posting
        editedAt:
          type: string
          format: date-time
          nullable: true
        editCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        replies:
          type: array
          items:
            $ref: '#/components/schemas/ResponseNode'
          description: Nested replies (recursive structure)

    Citation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        originalUrl:
          type: string
        normalizedUrl:
          type: string
        title:
          type: string
          nullable: true
        validationStatus:
          type: string
          enum: [UNVERIFIED, VALID, INVALID, BROKEN]
        validatedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time

    UserSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        displayName:
          type: string
        avatarUrl:
          type: string
          nullable: true

    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
        totalPages:
          type: integer
        totalItems:
          type: integer
        itemsPerPage:
          type: integer
        hasNextPage:
          type: boolean
        hasPreviousPage:
          type: boolean

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string
        validationErrors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
