openapi: 3.0.3
info:
  title: Response API
  description: API for managing responses within discussions (create, edit, delete, reply)
  version: 1.0.0

paths:
  /responses:
    post:
      summary: Create a top-level response
      description: Post a new top-level response to a discussion
      operationId: createResponse
      tags:
        - responses
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResponseRequest'
      responses:
        '201':
          description: Response created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDetail'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - user suspended or deleted
        '404':
          description: Discussion not found
        '429':
          description: Rate limit exceeded (10 responses per minute)

  /responses/{responseId}/replies:
    post:
      summary: Reply to a response
      description: Post a threaded reply to an existing response
      operationId: replyToResponse
      tags:
        - responses
      security:
        - bearerAuth: []
      parameters:
        - name: responseId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: ID of the parent response to reply to
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReplyRequest'
      responses:
        '201':
          description: Reply created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDetail'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Parent response not found
        '429':
          description: Rate limit exceeded (10 responses per minute)

  /responses/{responseId}:
    put:
      summary: Edit a response
      description: Edit own response content (with optimistic locking to prevent conflicts)
      operationId: editResponse
      tags:
        - responses
      security:
        - bearerAuth: []
      parameters:
        - name: responseId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditResponseRequest'
      responses:
        '200':
          description: Response edited successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDetail'
        '400':
          description: Validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - not the response author or edit window expired (24h)
        '404':
          description: Response not found
        '409':
          description: Conflict - response was modified by another operation (version mismatch)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictErrorResponse'
        '422':
          description: Unprocessable - response has been cited in common ground analysis

    delete:
      summary: Delete a response
      description: Delete own response (soft delete if has replies, hard delete otherwise)
      operationId: deleteResponse
      tags:
        - responses
      security:
        - bearerAuth: []
      parameters:
        - name: responseId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Response deleted (soft delete with placeholder)
          content:
            application/json:
              schema:
                type: object
                properties:
                  deletionType:
                    type: string
                    enum: [SOFT, HARD]
                  message:
                    type: string
        '204':
          description: Response permanently deleted (hard delete)
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - not the response author
        '404':
          description: Response not found

    get:
      summary: Get response details
      description: Get a single response with its thread (replies)
      operationId: getResponse
      tags:
        - responses
      security:
        - bearerAuth: []
      parameters:
        - name: responseId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Response details with replies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseDetail'
        '401':
          description: Unauthorized
        '404':
          description: Response not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CreateResponseRequest:
      type: object
      required:
        - discussionId
        - content
      properties:
        discussionId:
          type: string
          format: uuid
          description: ID of the discussion to respond to
        content:
          type: string
          minLength: 50
          maxLength: 25000
          description: Response content (max 5,000 words ≈ 25,000 chars)
        citations:
          type: array
          maxItems: 10
          items:
            $ref: '#/components/schemas/CitationInput'

    CreateReplyRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          minLength: 50
          maxLength: 25000
          description: Reply content (max 5,000 words ≈ 25,000 chars)
        citations:
          type: array
          maxItems: 10
          items:
            $ref: '#/components/schemas/CitationInput'

    EditResponseRequest:
      type: object
      required:
        - content
        - version
      properties:
        content:
          type: string
          minLength: 50
          maxLength: 25000
          description: Updated response content
        version:
          type: integer
          minimum: 1
          description: Current version for optimistic locking (must match DB version)
        citations:
          type: array
          maxItems: 10
          items:
            $ref: '#/components/schemas/CitationInput'
          description: Updated citation list (replaces existing)

    CitationInput:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: uri
          maxLength: 2048
          description: Citation URL (will be validated for SSRF attacks)
        title:
          type: string
          maxLength: 500
          description: Optional citation title/description

    ResponseDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        discussionId:
          type: string
          format: uuid
        parentId:
          type: string
          format: uuid
          nullable: true
          description: Parent response ID (null for top-level responses)
        author:
          $ref: '#/components/schemas/UserSummary'
        content:
          type: string
          description: Response content (may be "[deleted by author]" for soft-deleted)
        citations:
          type: array
          items:
            $ref: '#/components/schemas/Citation'
        version:
          type: integer
          description: Current version for optimistic locking
        isDeleted:
          type: boolean
          description: True if soft-deleted
        deletedAt:
          type: string
          format: date-time
          nullable: true
        isEdited:
          type: boolean
          description: True if edited after posting
        editedAt:
          type: string
          format: date-time
          nullable: true
        editCount:
          type: integer
          description: Number of times edited
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        replies:
          type: array
          items:
            $ref: '#/components/schemas/ResponseDetail'
          description: Nested replies (recursive structure)
        threadDepth:
          type: integer
          description: Nesting level (0 = top-level, 1 = first reply, etc.)
        canEdit:
          type: boolean
          description: Whether current user can edit (within 24h window)
        canDelete:
          type: boolean
          description: Whether current user can delete

    Citation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        originalUrl:
          type: string
          description: URL as submitted by user
        normalizedUrl:
          type: string
          description: Normalized URL for deduplication
        title:
          type: string
          nullable: true
          description: Citation title/description
        validationStatus:
          type: string
          enum: [UNVERIFIED, VALID, INVALID, BROKEN]
          description: URL validation status (checked async)
        validatedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time

    UserSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        displayName:
          type: string
        avatarUrl:
          type: string
          nullable: true

    ErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
        message:
          type: string
        error:
          type: string
        validationErrors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

    ConflictErrorResponse:
      type: object
      properties:
        statusCode:
          type: integer
          example: 409
        message:
          type: string
          example: "Response was modified by another operation. Please refresh and try again."
        error:
          type: string
          example: "Conflict"
        currentVersion:
          type: integer
          description: Current version in database
        providedVersion:
          type: integer
          description: Version provided in request
