name: Delete merged branch

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

concurrency:
  group: delete-branch-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, linux]
    steps:
      - name: Delete head branch
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/git/refs/heads/{branch}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          branch: ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
